/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kc98 (https://sketchfab.com/kirbycano98)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chainsaw-man-darkness-demon-8218cc69a7a244ecbe49f842d9d882c7
Title: Chainsaw man - Darkness demon
*/

import { useGLTF } from "@react-three/drei";
import { useSpring, a } from '@react-spring/three';
import { useModelStore } from "@/lib/zustand/modelStore";

export default function Astronaut(props: any) {
    const { nodes, materials }: any = useGLTF("/models/chainsawman-astronaut.glb");
    const { animate } = useModelStore();
    const separation: number = 200; 

    const { posAnim } = useSpring({
        posAnim: [(animate ? 1600 : -2000), 180, -400],
        config: { mass: 10, tension: 600, friction: 200},
    });

    return (
        <a.group {...props} dispose={null} position={posAnim}>
            <group
                position={[-915.913, 2.439, -74.147 + separation]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.HelmetGlass001_HelmetGlass_0.geometry}
                    material={materials.HelmetGlass}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.HelmetGlass001_Rim_0.geometry}
                    material={materials.material}
                />
            </group>
            <group
                position={[-856.386, -766.475, -102.908 + separation]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Accesories001_Material2_0.geometry}
                    material={materials.Material2}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Accesories001_Rim_0.geometry}
                    material={materials.material}
                />
            </group>
            <group
                position={[-856.386, -14.72, 777.155 - separation]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={100}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.LowerBody_Material2_0.geometry}
                    material={materials.Material2}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.LowerBody_Material_0.geometry}
                    material={materials.Material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.LowerBody_Rim_0.geometry}
                    material={materials.material}
                />
            </group>
            <group
                position={[-916.904, -800, -91.046 + separation]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            >
                <primitive object={nodes._rootJoint} />
                <group position={[0.605, 0.119, 0.395]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.UpperBody001_Material_0.geometry}
                        material={materials.Material}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.UpperBody001_Material2_0.geometry}
                        material={materials.Material2}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.UpperBody001_Rim_0.geometry}
                        material={materials.material}
                    />
                </group>
            </group>
            {/* <mesh
                castShadow
                receiveShadow
                geometry={nodes.Suzanne001_Material_0.geometry}
                material={materials.Material}
                position={[-915.913, -7.344, -70.466]}
                rotation={[-1.551, 0, 0]}
                scale={64.025}
            /> */}
            {/* <mesh
                castShadow
                receiveShadow
                geometry={nodes.GrassBlade_Grass_0.geometry}
                material={materials.Grass}
                position={[-353.498, -450.275, 317.104]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane001_Grass_0.geometry}
                material={materials.Grass}
                position={[24.408, -392.509, 393.781]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={689.427}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane_Grass_0.geometry}
                material={materials.Grass}
                position={[-926.864, -386.199, 142.156]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={121.27}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.GrassBlade001_Grass_0.geometry}
                material={materials.Grass}
                position={[-513.547, -424.064, 317.104]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Ground_Ground_0.geometry}
                material={materials.Ground}
                position={[0, -386.201, 399.354]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={2601.285}
            /> */}
        </a.group>
    );
}

useGLTF.preload("/models/chainsawman-astronaut.glb");